# Generated by Django 4.0.6 on 2022-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=250)),
                ('Surname', models.TextField(max_length=250)),
                ('Birth_Date', models.DateField()),
                ('Employee_Number', models.CharField(max_length=250)),
                ('Salary', models.BigIntegerField()),
                ('Role_Description', models.TextField(max_length=250)),
                ('Reporting_Line', models.TextField(max_length=250)),
            ],
        ),
    ]
