# Generated by Django 4.1 on 2022-08-27 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetable',
            name='Reporting_person',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='Name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='Reporting_Line',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='Role_Description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employeetable',
            name='Surname',
            field=models.CharField(max_length=250),
        ),
    ]
